// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

struct csum_inet {
  uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
  csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data,
                             size_t length)
{
  if (length == 0)
    return;
  size_t i = 0;
  for (; i < length - 1; i += 2)
    csum->acc += *(uint16_t*)&data[i];
  if (length & 1)
    csum->acc += le16toh((uint16_t)data[length - 1]);
  while (csum->acc > 0xffff)
    csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
  return ~csum->acc;
}

struct mac_addr {
  uint32_t a0;
  uint16_t a1;
};

struct mac_addr_def {
  uint8_t addr[6];
};

static long syz_mac_addr_gen(volatile long a0, volatile long a1,
                             volatile long a2)
{
  struct mac_addr_def* addr = (struct mac_addr_def*)a0;
  uint32_t* part1 = (uint32_t*)a1;
  uint16_t* part2 = (uint16_t*)a2;
  *part1 = (addr->addr[3] << 24) | (addr->addr[2] << 16) |
           (addr->addr[1] << 8) | addr->addr[0];
  *part2 = (addr->addr[5] << 8) | addr->addr[4];
  return 0;
}

uint64_t r[2] = {0x0, 0x0};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffffffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200000000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x200001000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul,
          /*fd=*/(intptr_t)-1, /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memset((void*)0x200000000100, 255, 6);
  res = -1;
  res = syz_mac_addr_gen(/*addr=*/0x200000000100,
                         /*mac_addr_part1=*/0x200000000140,
                         /*mac_addr_part2=*/0x200000000180);
  if (res != -1) {
    r[0] = *(uint32_t*)0x200000000140;
    r[1] = *(uint16_t*)0x200000000180;
  }
  *(uint32_t*)0x200000000a80 = r[0];
  *(uint16_t*)0x200000000a84 = r[1];
  *(uint32_t*)0x200000000a86 = 0;
  *(uint16_t*)0x200000000a8a = 0;
  *(uint16_t*)0x200000000a8c = htobe16(0x86dd);
  STORE_BY_BITMASK(uint8_t, , 0x200000000a8e, 0, 0, 4);
  STORE_BY_BITMASK(uint8_t, , 0x200000000a8e, 6, 4, 4);
  memcpy((void*)0x200000000a8f, "\xdf\xae\x56", 3);
  *(uint16_t*)0x200000000a92 = htobe16(0x14);
  *(uint8_t*)0x200000000a94 = 6;
  *(uint8_t*)0x200000000a95 = -1;
  *(uint64_t*)0x200000000a96 = 0;
  *(uint64_t*)0x200000000a9e = 0;
  *(uint64_t*)0x200000000aa6 = 0;
  *(uint64_t*)0x200000000aae = 0;
  *(uint16_t*)0x200000000ab6 = 0;
  *(uint16_t*)0x200000000ab8 = 0;
  *(uint32_t*)0x200000000aba = 0x41424344;
  *(uint32_t*)0x200000000abe = 0x41424344;
  STORE_BY_BITMASK(uint8_t, , 0x200000000ac2, 1, 0, 1);
  STORE_BY_BITMASK(uint8_t, , 0x200000000ac2, 0, 1, 3);
  STORE_BY_BITMASK(uint8_t, , 0x200000000ac2, 5, 4, 4);
  *(uint8_t*)0x200000000ac3 = 0xc1;
  *(uint16_t*)0x200000000ac4 = htobe16(0);
  *(uint16_t*)0x200000000ac6 = htobe16(0);
  *(uint16_t*)0x200000000ac8 = htobe16(6);
  struct csum_inet csum_1;
  csum_inet_init(&csum_1);
  csum_inet_update(&csum_1, (const uint8_t*)0x200000000a96, 16);
  csum_inet_update(&csum_1, (const uint8_t*)0x200000000aa6, 16);
  uint32_t csum_1_chunk_2 = 0x14000000;
  csum_inet_update(&csum_1, (const uint8_t*)&csum_1_chunk_2, 4);
  uint32_t csum_1_chunk_3 = 0x6000000;
  csum_inet_update(&csum_1, (const uint8_t*)&csum_1_chunk_3, 4);
  csum_inet_update(&csum_1, (const uint8_t*)0x200000000ab6, 20);
  *(uint16_t*)0x200000000ac6 = csum_inet_digest(&csum_1);
  syz_emit_ethernet_tcp(/*len=*/0x4a, /*packet=*/0x200000000a80, /*frags=*/0);
  return 0;
}
