// Automatically generated by syz-sysgen; DO NOT EDIT.

package sys

import (
	"embed"

	"github.com/google/syzkaller/sys/generated"

	"github.com/google/syzkaller/sys/darwin"
	"github.com/google/syzkaller/sys/freebsd"
	"github.com/google/syzkaller/sys/fuchsia"
	"github.com/google/syzkaller/sys/linux"
	"github.com/google/syzkaller/sys/netbsd"
	"github.com/google/syzkaller/sys/openbsd"
	"github.com/google/syzkaller/sys/test"
	"github.com/google/syzkaller/sys/trusty"
	"github.com/google/syzkaller/sys/windows"
)

//go:embed gen/*.gob.flate
var files embed.FS

func init() {
	generated.Register("darwin", "amd64", "872bba2ae5409477b673378e8bd7f3c4cb76fb57", darwin.InitTarget, files)
	generated.Register("freebsd", "386", "705e3665a4390df90af12368202a50353f41ecb2", freebsd.InitTarget, files)
	generated.Register("freebsd", "amd64", "945d95af847241e5b03a2d33af13fb49bfb9d839", freebsd.InitTarget, files)
	generated.Register("freebsd", "arm64", "945d95af847241e5b03a2d33af13fb49bfb9d839", freebsd.InitTarget, files)
	generated.Register("freebsd", "riscv64", "945d95af847241e5b03a2d33af13fb49bfb9d839", freebsd.InitTarget, files)
	generated.Register("fuchsia", "amd64", "964c7fd4b1c8b2f056ea0047c6f157b808eace6d", fuchsia.InitTarget, files)
	generated.Register("fuchsia", "arm64", "aabea56d7a220b467494a72b09e415bcfe2e82a0", fuchsia.InitTarget, files)
	generated.Register("linux", "386", "ae7996a3faec86b5afeebe1648529732186307bc", linux.InitTarget, files)
	generated.Register("linux", "amd64", "301692cd0aa7cf8050c3a8a41879f8ece93a3f04", linux.InitTarget, files)
	generated.Register("linux", "arm", "d6b1a496e8f75c226aee8cf258887b4b5e557e9f", linux.InitTarget, files)
	generated.Register("linux", "arm64", "c980724bbcbd65db3cf3fae33b771bed4f27e350", linux.InitTarget, files)
	generated.Register("linux", "mips64le", "705b82f5adac489a93c46c535115669e29d86e18", linux.InitTarget, files)
	generated.Register("linux", "ppc64le", "85e85e3010d2db609cce652293cb0a519f77384c", linux.InitTarget, files)
	generated.Register("linux", "riscv64", "0f58bb32b51b14c987ca054f864fcf5eb72566d6", linux.InitTarget, files)
	generated.Register("linux", "s390x", "643f81c585ff4dbbcacb46d3e816255119d41164", linux.InitTarget, files)
	generated.Register("netbsd", "amd64", "e55c41320cbb764d170d09a2ed5dbe024471a081", netbsd.InitTarget, files)
	generated.Register("openbsd", "amd64", "28e2a779b374e0bdb00904ce8937a588324093e6", openbsd.InitTarget, files)
	generated.Register("test", "32", "774bd1833e3c8b50f116747de65cf245dbbe7492", test.InitTarget, files)
	generated.Register("test", "32_fork", "b11ab04652e27605ae4a1816ebf7989860974245", test.InitTarget, files)
	generated.Register("test", "64", "3f4c92b9a77e3109f812dc47cdb5d09ecbecd741", test.InitTarget, files)
	generated.Register("test", "64_fork", "0282491ed7d87770001881623ce2ff0bd544caff", test.InitTarget, files)
	generated.Register("test", "64_fuzz", "2fdc070f08aa526d39a3f3e403d6624b1ac963bd", test.InitTarget, files)
	generated.Register("trusty", "arm", "e15883cf9bc294d71c2d4e06d02c4bda0414a94f", trusty.InitTarget, files)
	generated.Register("windows", "amd64", "f14e4fef7483fea72b1b0867de524882897680c6", windows.InitTarget, files)

}
